### ISSUE TITLE
安装好麻烦

### ISSUE THREAD

**Issue by Jie-Yuan** [hankcs/pyhanlp#10]
![image](https://user-images.githubusercontent.com/20265321/38182841-b26aadce-366e-11e8-819d-887c6f9a9b62.png)
按照文档手动配置任然有错

**Comment by hankcs** [comment]
1. 你说你已经按照文档手动配置，那么请运行如下命令验证

```
tree $HANLP_STATIC_ROOT
ll $HANLP_JAR_PATH
cat $HANLP_STATIC_ROOT/hanlp.properties
```

**Comment by Jie-Yuan** [comment]
求助
![image](https://user-images.githubusercontent.com/20265321/38183867-4034db50-3676-11e8-80e0-7f80788c8c4b.png)

**Comment by hankcs** [comment]
奇怪，现在代码逻辑是如果这两个环境变量存在则根本不会去static加载。请在同一个窗口内试试Python能不能获取这个变量：

```
python3
>>> import os
>>> ENVIRON = os.environ.copy()
>>> ENVIRON["HANLP_STATIC_ROOT"]
'/Users/hankcs/PythonProjects/pyhanlp/pyhanlp/static'
>>> ENVIRON["HANLP_JAR_PATH"]
'/Users/hankcs/PythonProjects/pyhanlp/pyhanlp/static/hanlp-1.6.2.jar'
```

**Comment by hankcs** [comment]
```
pip install pyhanlp==0.1.32
```

应该解决了这个问题。
