### ISSUE TITLE
python2.x的问题

### ISSUE THREAD

**Issue by bojone** [hankcs/pyhanlp#11]
static/__init__.py文件第255行为：

open(PATH_CONFIG, encoding='utf-8') as f:

显然这在py2下是不可行的。py2下要用codecs.open才有encoding参数。

**Comment by hankcs** [comment]
感谢指正，欢迎测试

```
pip install pyhanlp==0.1.33
```

**Comment by hankcs** [comment]
问题应该解决了，如果还有问题，欢迎重开issue。
