### ISSUE TITLE
安装hanlp错误

### ISSUE THREAD

**Issue by Lollipop77** [hankcs/pyhanlp#13]
pip install pyhanlp
之后：

Extracting data.zip...
Traceback (most recent call last):
  File "/usr/bin/hanlp", line 7, in <module>
    from pyhanlp.main import main
  File "/usr/lib/python2.7/site-packages/pyhanlp/__init__.py", line 113, in <module>
    CustomDictionary = SafeJClass('com.hankcs.hanlp.dictionary.CustomDictionary')
  File "/usr/lib/python2.7/site-packages/pyhanlp/__init__.py", line 99, in __init__
    self._proxy = JClass(proxy) if type(proxy) is str else proxy
  File "/usr/lib/python2.7/site-packages/jpype/_jclass.py", line 73, in JClass
    raise _RUNTIMEEXCEPTION.PYEXC("Class %s not found" % name)
jpype._jexception.RuntimeExceptionPyRaisable: java.lang.RuntimeException: Class com.hankcs.hanlp.dictionary.CustomDictionary not found

运行于cygwin64  
Python: python 2.7.14

**Comment by hankcs** [comment]
请问/usr/lib/python2.7/site-packages/pyhanlp/目录下有hanlp-1.6.2.jar文件吗？

**Comment by Lollipop77** [comment]
你好
没有 需要加到这个目录下吗？ 还需要加入什么文件

**Comment by hankcs** [comment]
下载 http://nlp.hankcs.com/download.php?file=jar ，解压将hanlp-1.6.2.jar加到这个目录应该就可以了。

顺便问一下，首次运行的时候应该会自动下载release.zip的，没有触发吗？

**Comment by Lollipop77** [comment]
没有

**Comment by Lollipop77** [comment]
没有

**Comment by Lollipop77** [comment]
没有
最开始出现jpype1的问题 解决后又重开Terminal运行，出现如下代码：
$ pip install pyhanlp
Collecting pyhanlp
Collecting jpype1 (from pyhanlp)
  Using cached JPype1-0.6.3.tar.gz
Building wheels for collected packages: jpype1
  Running setup.py bdist_wheel for jpype1 ... done
  Stored in directory: /home/NEWFT/.cache/pip/wheels/56/23/bd/3d39939f5a3eac3520                                                                                                                                         709d2eb3abcbd2301d5f052f6e99765d
Successfully built jpype1
Installing collected packages: jpype1, pyhanlp
Successfully installed jpype1-0.6.3 pyhanlp-0.1.34
以及
Downloading https://github.com/hankcs/HanLP/releases/download/v1.6.2/hanlp-1.6.2                                                                                                                                         -release.zip to /usr/lib/python2.7/site-packages/pyhanlp/static/hanlp-1.6.2-rele                                                                                                                                         ase.zip
100.00%, 1 MB, 786 KB/s, ETA 0 min 0 s
Downloading http://hanlp.linrunsoft.com/release/data-for-1.6.2.zip to /usr/lib/p                                                                                                                                         ython2.7/site-packages/pyhanlp/static/data-for-1.6.2.zip
68.60%, 455 MB, 630 KB/s, ETA 5 min 38 s--2018-04-09 17:44:38--  http://hanlp.li                                                                                                                                         nrunsoft.com/release/data-for-1.6.2.zip
Résolution de hanlp.linrunsoft.com (hanlp.linrunsoft.com)… 115.29.171.123
Connexion à hanlp.linrunsoft.com (hanlp.linrunsoft.com)|115.29.171.123|:80… conn                                                                                                                                         ecté.
requête HTTP transmise, en attente de la réponse… 200 OK
Taille : 696603713 (664M) [application/zip]
Sauvegarde en : « /usr/lib/python2.7/site-packages/pyhanlp/static/data-for-1.6.2                                                                                                                                         .zip.downloading »

/usr/lib/python2.7/site-packages/pyhanlp/static/data-f 100%[=========================================================================================================================>] 664,33M   513KB/s    ds 27m 8s

2018-04-09 18:11:47 (418 KB/s) — « /usr/lib/python2.7/site-packages/pyhanlp/static/data-for-1.6.2.zip.downloading » sauvegardé [696603713/696603713]

Extracting data.zip...
Traceback (most recent call last):
  File "/usr/bin/hanlp", line 7, in <module>
    from pyhanlp.main import main
  File "/usr/lib/python2.7/site-packages/pyhanlp/__init__.py", line 113, in <module>
    CustomDictionary = SafeJClass('com.hankcs.hanlp.dictionary.CustomDictionary')
  File "/usr/lib/python2.7/site-packages/pyhanlp/__init__.py", line 99, in __init__
    self._proxy = JClass(proxy) if type(proxy) is str else proxy
  File "/usr/lib/python2.7/site-packages/jpype/_jclass.py", line 73, in JClass
    raise _RUNTIMEEXCEPTION.PYEXC("Class %s not found" % name)
jpype._jexception.RuntimeExceptionPyRaisable: java.lang.RuntimeException: Class com.hankcs.hanlp.dictionary.CustomDictionary not found

***************************************************************************

问题还存在：
NEWFT@FT-PC /usr/lib/python2.7/site-packages/pyhanlp
$ pip install pyhanlp
Requirement already satisfied: pyhanlp in /usr/lib/python2.7/site-packages
Requirement already satisfied: jpype1 in /usr/lib/python2.7/site-packages (from pyhanlp)

NEWFT@FT-PC /usr/lib/python2.7/site-packages/pyhanlp
$ hanlp
Traceback (most recent call last):
  File "/usr/bin/hanlp", line 7, in <module>
    from pyhanlp.main import main
  File "/usr/lib/python2.7/site-packages/pyhanlp/__init__.py", line 113, in <module>
    CustomDictionary = SafeJClass('com.hankcs.hanlp.dictionary.CustomDictionary')
  File "/usr/lib/python2.7/site-packages/pyhanlp/__init__.py", line 99, in __init__
    self._proxy = JClass(proxy) if type(proxy) is str else proxy
  File "/usr/lib/python2.7/site-packages/jpype/_jclass.py", line 73, in JClass
    raise _RUNTIMEEXCEPTION.PYEXC("Class %s not found" % name)
jpype._jexception.RuntimeExceptionPyRaisable: java.lang.RuntimeException: Class com.hankcs.hanlp.dictionary.CustomDictionary not found

NEWFT@FT-PC /usr/lib/python2.7/site-packages/pyhanlp
$ ls
__init__.py  __init__.pyc  hanlp-1.6.2.jar  main.py  main.pyc  server.py  static  util.py  util.pyc

**Comment by hankcs** [comment]
你的数据下载完全正常，我估计是cygwin的兼容问题。麻烦运行一下：

```
cd /usr/lib/python2.7/site-packages/pyhanlp/static
ls
cat hanlp.properties | grep root
```

**Comment by Lollipop77** [comment]
NEWFT@FT-PC /usr/lib/python2.7/site-packages/pyhanlp/static
$ ls
__init__.py  __init__.pyc  data  hanlp.properties  hanlp.properties.in  hanlp-1.6.2.jar  index.html

NEWFT@FT-PC /usr/lib/python2.7/site-packages/pyhanlp/static
$ cat hanlp.properties | grep root
root=/usr/lib/python2.7/site-packages/pyhanlp/static

**Comment by hankcs** [comment]
有意思，cygwin可以调用宿主机的java吗？

麻烦在python中验证这一点：

```
from jpype import *
startJVM(getDefaultJVMPath())
java.lang.System.out.println("hello world")
shutdownJVM()
```

其实Windows上可以直接跑pyhanlp，不需要cygwin的：https://github.com/hankcs/pyhanlp/wiki/Windows

**Comment by hankcs** [comment]
问题搞清楚了，cygwin使用了虚拟的路径，jvm访问不到。bug应该修复了，请试试：

```
pip2 install pyhanlp==0.1.37
```

![2018-04-09_19-07-02](https://user-images.githubusercontent.com/5326890/38529287-995bf016-3c29-11e8-829c-0b6ab0cd9352.png)

**Comment by Lollipop77** [comment]
没问题了，感谢。

**Comment by keyboardWitch** [comment]
我在运行时候总是报错：raise _RUNTIMEEXCEPTION.PYEXC("Class %s not found" % name)
查了一下 有说是jdk版本问题，请问当前java环境所需版本是多少？

**Comment by hankcs** [comment]
1.6以上，建议1.8
