### ISSUE TITLE
python3.6使用pyhanlp不能进行debug

### ISSUE THREAD

**Issue by nightxing** [hankcs/pyhanlp#14]
我在测试pyhanlp时，发现可以正常进行分词和自定义字典，但是不能进行debug，如果进行debug的话会直接退出，Process finished with exit code -1073741819 (0xC0000005)。
这导致我项目中不能使用pyhanlp，这样就不能进行测试了。
然后解决办法是当成黑箱，不对分词这一部分的代码就行debug，直接当成方法调用，是没问题的，
最近因为发现人名获取不理想，改用感知机分词，但是问题出现了，把分词写成方法一样不能使用了，debug会直接报错，多线程的项目也不能进行。我想知道怎么解决！谢谢大佬帮助

**Comment by hankcs** [comment]
1. macOS debug正常，估计Linux也正常。
1. 最新版已经解决了多线程，用SafeJClass就行了。

<img width="641" alt="hankcs com 2018-04-13 10 59 20" src="https://user-images.githubusercontent.com/5326890/38745372-f34fdc26-3f09-11e8-8a36-681ad4974188.png">

**Comment by hankcs** [comment]
问题应该解决了，如果还有问题，欢迎重开issue。
