### ISSUE TITLE
感知机分词学习，词性不能正确显示

### ISSUE THREAD

**Issue by nightxing** [hankcs/pyhanlp#15]
感知机分词，在线学习之后，能够成功分词，但是词性有问题
这是代码：
PerceptronLexicalAnalyzer = JClass('com.hankcs.hanlp.model.perceptron.PerceptronLexicalAnalyzer')
analyzer = PerceptronLexicalAnalyzer()
print(analyzer.seg('与特朗普通电话讨论太空探索技术公司'))
analyzer.learn("与/c 特朗普/nr 通/v 电话/n 讨论/v [太空/s 探索/vn 技术/n 公司/n]/nt")
print(analyzer.seg('与特朗普通电话讨论太空探索技术公司'))

这是输出结果：
[与/p, 特朗/n, 普通/a, 电话/n, 讨论/v, 太空/s, 探索/vn, 技术/n, 公司/n]
[与/c, 特朗普/nr, 通/v, 电话/n, 讨论/v, 太空探索技术公司/n]

这里的nt不能正确显示！

顺便问一句，这里的词性能自动添加自定义词性吗？比如将公司名称标记为company

**Comment by hankcs** [comment]
1. hanlp update jar和data至最新版本
1. 测试一切正常：总统/n 普京/nr 与/c 特朗普/nr 通/v 电话/n 讨论/v [太空/s 探索/vn 技术/n 公司/n]/nt

**Comment by nightxing** [comment]
hanlp update jar
usage: hanlp [-h] [-v] {segment,parse,serve,update} ...
hanlp: error: unrecognized arguments: jar

**Comment by hankcs** [comment]
hanlp update

**Comment by nightxing** [comment]
pip install --upgrade pyhanlp
Requirement already up-to-date: pyhanlp in d:\appdev\anaconda\lib\site-packages
Requirement already up-to-date: jpype1 in d:\appdev\anaconda\lib\site-packages (from pyhanlp)

hanlp update
HanLP jar is already the latest version 1.6.3

windows10，依然不能正确显示在线学习的词性

analyzer.learn("与/c 特朗普/nr 通/v 电话/n 讨论/v [太空/s 探索/vn 技术/n 公司/n]/nt")
输出结果
[与/c, 特朗普/nr, 通/v, 电话/n, 讨论/v, 太空探索技术公司/n]

**Comment by hankcs** [comment]
1. 请确认data是1.6.2，手动安装的data不会自动更新
1. 请确认是否外挂了词典`analyzer.enableCustomDictionary(false)`，是否保存过在线学习的模型
1. 你还可以多执行几遍learn试试

**Comment by nightxing** [comment]
Downloading https://github.com/hankcs/HanLP/releases/download/v1.6.3/hanlp-1.6.3-release.zip to D:\appdev\anaconda\lib\site-packages\pyhanlp\static\hanlp-1.6.3-release.zip
100.00%, 1 MB, 354 KB/s, ETA 0 min 0 s
Downloading http://hanlp.linrunsoft.com/release/data-for-1.6.2.zip to D:\appdev\anaconda\lib\site-packages\pyhanlp\static\data-for-1.6.2.zip
100.00%, 664 MB, 1421 KB/s, ETA 0 min 0 s
Extracting data.zip...
[计算机/n, 硬件/n]
[与/c, 特朗普/nr, 通/v, 电话/n, 讨论/v, 太空探索技术公司/n]

表示windows下这个词性标注不好用啊，这是全新安装的一个pyhanlp，数据，配置文件都是默认的，代码也很简单：
analyzer = PerceptronLexicalAnalyzer()
print(analyzer.seg('计算机硬件'))
for i in range(100):
    analyzer.learn("与/c 特朗普/nr 通/v 电话/n 讨论/v [太空/s 探索/vn 技术公司/n]/nt")
print(analyzer.seg('与特朗普通电话讨论太空探索技术公司'))

循环学习100遍还是不能正确显示词性！

另外，我们需要自定义一些标签还进行属性标注，用你们java的训练都成功了，但是分词还是分不出来。那个训练可以自定义新标签吗？[太空/s 探索/vn 技术/n 公司/n]/company

求指导，现在卡到这里了

**Comment by hankcs** [comment]
谨遵医嘱！analyzer.enableCustomDictionary(False)

**Comment by hankcs** [comment]
感谢反馈，seg接口的确有个bug。欢迎使用补丁jar替换安装路径下的jar：
[hanlp-1.6.3.jar.zip](https://github.com/hankcs/pyhanlp/files/1929462/hanlp-1.6.3.jar.zip)
