### ISSUE TITLE
自定义字典没有效果

### ISSUE THREAD

**Issue by stevewyl** [hankcs/pyhanlp#16]
我在custom文件夹下增加了一个文本文件用于放置一些专有名词，需要被正确切分。
词典中的词格式设置如下
![1523713512](https://user-images.githubusercontent.com/12755003/38768913-2a805404-402d-11e8-95a2-a3300c0be99b.png)
配置文件的设置如下
![image](https://user-images.githubusercontent.com/12755003/38768922-4bee0ab4-402d-11e8-85df-4df4eb46f65f.png)
文件目录的截图如下：
![image](https://user-images.githubusercontent.com/12755003/38768929-6553460e-402d-11e8-8a98-d38dfc5461d9.png)

最终结果如下，与没加词典前的结果是一致的
![image](https://user-images.githubusercontent.com/12755003/38768937-77b14738-402d-11e8-86e4-5247ff32ee9a.png)

在阅读HanLP主项目的文档是发现，可以通过设置Segment#enableCustomDictionaryForcing强制生效，不知道pyhanlp中如何设置这个参数？

系统及python环境：Windows10 Python3.6.4 HanLP1.6.2

**Comment by hankcs** [comment]
请参考 https://github.com/hankcs/pyhanlp/blob/master/tests/test_custom_dict.py

**Comment by stevewyl** [comment]
@hankcs 问题已解决 感谢！以后还得再仔细看文档再来提问。

**Comment by hankcs** [comment]
好的

**Comment by Yevgnen** [comment]
在Python里是否有方法像修改Java版的hanlp.properties一样，大量添加词典呢（只添加词典路径，而不是用`CustomDictionary.insert`一个一个加呢）？ `CustomDictionary`貌似有load方法，但在Python版里使用方式不是非常明了…

**Comment by stevewyl** [comment]
@Yevgnen 可以的 你首先要删除缓存文件 然后在hanlp.properties加入你字典的路径 重新启动一次hanlp，它会重新生成新的缓存文件的

**Comment by Yevgnen** [comment]
@stevewyl 我指用Python的话是不是可以不关心`hanlp.properties`这个文件，毕竟在`site-packages`里。我希望可以用一种在程序里添加词典路径的方法。如：`

```
for dict_ in ['a.txt', 'b.txt']:
        JClass('xxx.xxx.xxx').load(dict_)
```
