### ISSUE TITLE
HanLP.parseDependency()返回值的问题

### ISSUE THREAD

**Issue by fighting41love** [hankcs/pyhanlp#22]
感谢提供pyhanlp，方便python开发人员！
想问一个问题：

HanLP.parseDependency()返回的是CoNLLSentence类型。
请问一下，如何解析CoNLLSentence类型？有没有例子?

结果如下，HanLP.parseDependency()返回的结果能转变为 dict或list类型吗？谢谢！
1	李白	李白	nh	nr	_	3	定中关系	_	_
2	的	的	u	ude1	_	1	右附加关系	_	_
3	诗	诗	n	n	_	4	主谓关系	_	_
4	有	有	v	vyou	_	0	核心关系	_	_
5	哪些	哪些	r	ry	_	4	动宾关系	_	_
6	？	？	wp	w	_	4	标点符号	_	_

**Comment by fighting41love** [comment]
上面是java读取CoNLLSentence的代码吧，没怎么学过java。。。
有python解析的code吗？谢谢！

**Comment by hankcs** [comment]
请参考 https://github.com/hankcs/pyhanlp/blob/master/tests/demos/demo_dependency_parser.py

**Comment by fighting41love** [comment]
多谢了！如果有计算Dependency Tree任意两个节点之间的path的代码就更赞了，多谢！

**Comment by fighting41love** [comment]
dependency tree已经不是binary tree了，完全可以使用图来建模。所以，我采用了networkx，构建一个网络，使用graph上的shortest path，来计算该dependency tree上任意两个节点之间的距离。
