### ISSUE TITLE
jpype._jexception.java.lang.NoSuchMethodErrorPyRaisable: java.lang.NoSuchMethodError: sun.reflect.ReflectionFactory.newConstructorAccessor(Ljava/lang/reflect/Constructor;)Lsun/reflect/ConstructorAccessor;

### ISSUE THREAD

**Issue by jiangxubin** [hankcs/pyhanlp#28]
Python:Python 3.6.4 |Anaconda custom (64-bit)
Windows 10 64位
使用 NLPTokenizer出现上述错误
5�� 10, 2018 9:22:42 ���� com.hankcs.hanlp.corpus.util.CustomNatureUtility <clinit>
����: �Ѽ����Զ�����Թ���,���ڲ����˷��似��,�û���Ա��ػ����ļ����Ժ��ȶ��Ը���!
����û�����X.java����switch(nature)���,��Ҫ����CustomNatureUtility.registerSwitchClass(X.class)ע��X�����

**Comment by hankcs** [comment]
请参考：https://github.com/hankcs/HanLP/wiki/FAQ#%E5%8A%A0%E5%85%A5%E8%87%AA%E5%AE%9A%E4%B9%89%E8%AF%8D%E6%80%A7%E5%90%8E%E5%8F%91%E7%94%9Farrayindexoutofboundsexception
