### ISSUE TITLE
parseDependency 速度很慢

### ISSUE THREAD

**Issue by Samurais** [hankcs/pyhanlp#3]
我试了一下parseDependency的速度，感觉很慢。
现在jvm是申请了1GB的内存使用，在生产环境上是可以设置到32GB或者更大。

除了加内存，还有其他优化访问速度的方法吗？

**Comment by hankcs** [comment]
这是由于模型体积很大造成的，加载完毕后一秒钟大概能分析20个句子。参考：https://github.com/hankcs/HanLP/issues/551
