### ISSUE TITLE
卡在 Extracting data.zip...

### ISSUE THREAD

**Issue by crapthings** [hankcs/pyhanlp#31]
hanlp segment
Downloading https://github.com/hankcs/HanLP/releases/download/v1.6.4/hanlp-1.6.4-release.zip to /usr/local/lib/python2.7/site-packages/pyhanlp/static/hanlp-1.6.4-release.zip
100.00%, 1 MB, 538 KB/s, ETA 0 min 0 s
Downloading http://hanlp.linrunsoft.com/release/data-for-1.6.2.zip to /usr/local/lib/python2.7/site-packages/pyhanlp/static/data-for-1.6.2.zip
100.00%, 664 MB, 1883 KB/s, ETA 0 min 0 s
Extracting data.zip...

**Comment by hankcs** [comment]
在解压，耐心等待即可。

**Comment by crapthings** [comment]
好吧，单位的电脑 走时候开着早上确实过去了，家里一样的系统 卡在那里半天，回去重安试试，感谢
