### ISSUE TITLE
误判人名问题

### ISSUE THREAD

**Issue by yaleimeng** [hankcs/pyhanlp#37]
不太清楚是词典还是模型的问题，许多不该是人名的词被标注为/nr或/nrf，这些不恰当的词条导致分词也出现错误。有些词条我翻遍了词典也没查到，不能靠删除词条来解决问题。
注：hanlp数据版本1.6.4
例1：公司的章有红章有黑章，都是对方会认可的。
结果：公司/nis, 的/ude1, **章有红/nr**, **章有/nr**, 黑/a, 章/q, ，/w, **都是/nr**, 对/p, **方会/nr**, 认可/vn, 的/ude1, 。/w
例2：注意那张表金额要以元为单位，缩放为一页打印。
结果：注意/v, **那张表/nr**, 金额/n, 要/v, 以/p, **元为/nr**, 单位/n, ，/w, 缩放/gi, 为/p, 一/m, 页/q, 打印/v, 。/w
例3：那三年的年费能报销，这个季末测绘费能解决吗？
结果：**那三年/nr**, 的/ude1, **年费/nr**, 能/v, 报销/v, ，/w, 这个/rz, **季末/nr**, 测绘/vn, **费能/nr**, 解决/v, 吗/y, ？/w
例4：这张表到申报高新时才填。那还用加盖公章吗？
结果：这/rzv, **张表/nr**, 到/v, 申报/vn, **高新时/nr**, 才/d, 填/v, 。/w, **那还/nr**, 用/p, **加盖/nrf**, 公章/n, 吗/y, ？/w

**Comment by hankcs** [comment]
请参考文档 https://github.com/hankcs/HanLP#9-%E4%B8%AD%E5%9B%BD%E4%BA%BA%E5%90%8D%E8%AF%86%E5%88%AB

**Comment by hankcs** [comment]
另外，推荐使用感知机词法分析器。你可以通过[演示页面](http://hanlp.hankcs.com/?sentence=%E5%85%AC%E5%8F%B8%E7%9A%84%E7%AB%A0%E6%9C%89%E7%BA%A2%E7%AB%A0%E6%9C%89%E9%BB%91%E7%AB%A0%EF%BC%8C%E9%83%BD%E6%98%AF%E5%AF%B9%E6%96%B9%E4%BC%9A%E8%AE%A4%E5%8F%AF%E7%9A%84)比较两者的差别。

**Comment by yaleimeng** [comment]
多谢作者指点。
+ 感知机确实好了很多。前三句OK。
例4结果为：这/r, 张/q, **表到/v**, 申报/v, **高新时才/d**, 填/v, 。那/r, 还/d, 用/v, 加盖/v, 公章/n, 吗/y,
+ CRF分词略胜一筹：前三句也OK。
例4结果为：这/rzv, 张/q, 表/n, 到/v, 申报/vn, 高新/nz, 时/qt, 才/d, 填/v, 。/w, 那/rzv, 还/d, 用/p, **加盖/nrf**, 公章/n, 吗/y, ？/w
+ 另外人名问题可调节词典或者用person/nr.txt手动修正。其中词条后面跟着字母、数字（如 金花 K 20 Z 10 X 3 L 2）是什么含义呢？

**Comment by hankcs** [comment]
请阅读主项目文档引用的文献。
