### ISSUE TITLE
Ubuntu环境不能正确生成.bin文件？

### ISSUE THREAD

**Issue by yaleimeng** [hankcs/pyhanlp#38]
服务器系统：Ubuntu 16.04.1；pip方式安装，程序运行时自动下载并解压数据。
+ 当删除bin文件等它自动生成时，报告错误，意思是“找不到词典txt文件”，但路径和文件名都是没问题的，多次修改无效。然后也可以生成bin文件(<3MB)，但比Windows环境生成的bin文件（>16MB）小很多。而且经验证自定义词典未起作用。
+ 把Windows环境生成的bin文件放到服务器上之后，可以正常执行。所以怀疑是不是在该服务器环境是无法正确生成bin文件？

**Comment by hankcs** [comment]
项目现在主要在Linux下开发，不存在操作系统问题。“找不到词典txt文件”就是你的路径设置错误了，程序不会撒谎。你可以把配置文件贴出来看看。

**Comment by yaleimeng** [comment]
+ 配置文件为自动生成的，对应的目录是正确的：root=/usr/local/lib/python3.5/dist-packages/pyhanlp/static
+ 但我把CustomDictionary.txt.bin删除之后，运行 hanlp segment <<< '欢迎新老师生前来就餐' 
会提示找不到我的自定义词典文件。
+ 经过认真检查，发现通过Xftp工具将Win下的“某某某.txt”传到Linux服务器之后，文件名会变成乱码。引发这个报错。将文件名修改正确之后，故障消除。（Linux下正常的中文文件名，在Xftp中显示为乱码）
+ 总之，这是Xftp的锅。
