### ISSUE TITLE
请问如何在 NeuralNetworkDependencyParser 调用 NLPTokenizer 

### ISSUE THREAD

**Issue by remyhuang** [hankcs/pyhanlp#40]
我在使用 NeuralNetworkDependencyParser 时的分词结果与使用 NLPTokenizer 时的分词结果不同,
于是我想调用 NLPTokenizer 的分词结果再使用 NeuralNetworkDependencyParser.

想请问该如何调整?
谢谢!

**Comment by hankcs** [comment]
请仔细阅读文档。

**Comment by remyhuang** [comment]
谢谢，解决了！
