### ISSUE TITLE
json encoding error

### ISSUE THREAD

**Issue by ucaszx** [hankcs/pyhanlp#5]
Hi, hanks. It's really nice to have this python interface, and thanks for your enduring effort.
When i try to import pyhanlp in python3.5, I got this error

In [4]: from pyhanlp import *

TypeError                                 Traceback (most recent call last)
<ipython-input-4-4bdf2ccd9384> in <module>()
----> 1 from pyhanlp import *

/virtualenv/python35/lib/python3.5/site-packages/pyhanlp/__init__.py in <module>()
     27     STATIC_ROOT = ENVIRON["HANLP_STATIC_ROOT"]
     28 else:
---> 29     from pyhanlp.static import STATIC_ROOT
     30 
     31 HANLP_JAR_PATH = None

/virtualenv/python35/lib/python3.5/site-packages/pyhanlp/static/__init__.py in <module>()
    244 
    245 if not hanlp_installed_jar_versions():
--> 246     install_hanlp_jar()
    247 
    248 if not hanlp_installed_data_path():

/virtualenv/python35/lib/python3.5/site-packages/pyhanlp/static/__init__.py in install_hanlp_jar(version)
    159 def install_hanlp_jar(version=None):
    160     if version is None:
--> 161         version = hanlp_latest_version()[0]
    162     url = 'http://search.maven.org/remotecontent?filepath=com/hankcs/hanlp/portable-{}/hanlp-portable-{}.jar'.format(
    163         version, version)

/virtualenv/python35/lib/python3.5/site-packages/pyhanlp/static/__init__.py in hanlp_latest_version()
     54 
     55 def hanlp_latest_version():
---> 56     return hanlp_releases()[0]
     57 
     58 

/virtualenv/python35/lib/python3.5/site-packages/pyhanlp/static/__init__.py in hanlp_releases(cache)
     63     # print('Request GitHub API')
     64     content = urllib.urlopen("http://api.github.com/repos/hankcs/HanLP/releases").read()
---> 65     content = json.loads(content)
     66     meta = []
     67     for r in content:

/usr/local/python3.5/lib/python3.5/json/__init__.py in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    310     if not isinstance(s, str):
    311         raise TypeError('the JSON object must be str, not {!r}'.format(
--> 312                             s.__class__.__name__))
    313     if s.startswith(u'\ufeff'):
    314         raise JSONDecodeError("Unexpected UTF-8 BOM (decode using utf-8-sig)",

TypeError: the JSON object must be str, not 'bytes'

**Comment by hankcs** [comment]
GitHub API returns UTF-8 json file with BOM header, which is illegal in JSON specification. Please try the newly uploaded version:

```
pip3 uninstall hanlp -y
pip3 install pyhanlp --no-cache-dir
```

**Comment by ucaszx** [comment]
```
pip3 uninstall pyhanlp -y
pip3 uninstall JPype1 -y
pip3 install pyhanlp --no-cache-dir
```
It downloaded pyhanlp-0.1.7, and the problem remains.

**Comment by hankcs** [comment]
The latest version is much higher than that, please try this:

```
pip3 install pyhanlp==0.1.13
```

**Comment by ucaszx** [comment]
problem solved
