### ISSUE TITLE
多线程使用暴露性能问题

### ISSUE THREAD

**Issue by Samurais** [hankcs/pyhanlp#7]
我在多线程下使用 ， jpype 启动的JVM Crash了。
在其文档中有对性能的描述：
http://jpype.readthedocs.io/en/latest/userguide.html#overview

### JCC
http://lucene.apache.org/pylucene/jcc/install.html

比如pylucene 就是使用JCC。

还需要一些调研。

**Comment by hankcs** [comment]
看上去的确是个好方案，Apache品质有保障，需要试用一下。
我还知道py4j：https://www.py4j.org/ ，由于需要手工编写Java class与Python通讯，觉得比较麻烦就没有采用。

**Comment by hankcs** [comment]
我稍微试了一下:

1. JCC对Python3需要做点小改动
1. 会对每个Java class都生成一个.h，需要编译。所以需要一个持续集成工具来在各种平台下编译
1. 部分HanLP的接口无法包装

附件中有一个测试egg，调用方法如下：

```python
import hanlp
hanlp.initVM(classpath=hanlp.CLASSPATH + ':path/to/your/static/')
# noinspection PyUnresolvedReferences
from com.hankcs.hanlp.model.perceptron import PerceptronLexicalAnalyzer
analyzer = PerceptronLexicalAnalyzer()
print(analyzer.analyze("上海华安工业（集团）公司董事长谭旭光和秘书胡花蕊来到美国纽约现代艺术博物馆参观"))
# noinspection PyUnresolvedReferences
from com.hankcs.hanlp import HanLP
print(HanLP.parseDependency('商品和服务'))
```

[hanlp-0.0.0-py3.6-macosx-10.13-x86_64.egg.zip](https://github.com/hankcs/pyhanlp/files/1838760/hanlp-0.0.0-py3.6-macosx-10.13-x86_64.egg.zip)

**Comment by Samurais** [comment]
执行测试用例：
```
python tests/test_multithread.py
```

结果是:
![image](https://user-images.githubusercontent.com/3538629/37821837-b28c6826-2ebf-11e8-872d-172fbf51262a.png)

**Comment by Samurais** [comment]
相关问题分析：jpype Multithreading not working
https://github.com/originell/jpype/issues/211
