### ISSUE TITLE
import导致PerceptronLexicalAnalyzer加载

### ISSUE THREAD

**Issue by hankcs** [hankcs/pyhanlp#8]
https://github.com/hankcs/pyhanlp/blob/c04e998ad0e6f1aa0ff9194f58d9ff86a5265450/pyhanlp/__init__.py#L97

PerceptronLexicalAnalyzer的本意应该就是一个class，而不是一个object。因为PerceptronLexicalAnalyzer还可以接受不同的模型路径。现在这样会导致import时加载了模型，而实际上该模型不一定被使用。

**Comment by hankcs** [comment]
目前通过callable的方式模拟，应该解决了这个问题。麻烦检查是否还需在__call__里面attach_jvm_to_thread。

**Comment by yaleimeng** [comment]
以前一直通过jpype使用，但我在flask app中使用存在一些问题。。
作者终于要支持python了，好激动！！

**Comment by Samurais** [comment]
@yaleimeng 
pyhanlp支持多线程访问，比如Apache thrift 以及很多 Http Server  都是使用线程池处理socket请求。
pyhanlp也在测试阶段，如在使用过程中遇到问题，请帮忙建立issue。谢谢！

**Comment by hankcs** [comment]
@yaleimeng 
感谢使用，Python用户越来越多，我也经常用，所以干脆做个好用的。目前pyhanlp由我和 @Samurais 共同维护，欢迎广大Python用户参与开源项目，谢谢！

**Comment by hankcs** [comment]
这个bug应该解决了。
