### ISSUE TITLE
安装出错，求大佬帮忙

### ISSUE THREAD

**Issue by luluforever** [hankcs/pyhanlp#9]
显示UnicodeDecodeError错误

**Comment by luluforever** [comment]
在导入pyhanlp的时候同样出现了这个问题，前面安装的时候显示的是UnicodeDecodeError：‘utf_8’，然后我去吧pip里面代码改为‘gbk’,安装成功，但是导入pyhanlp的时候显示UnicodeDecodeError：‘gbk’,进了显示错误的文件里面，没有发现‘gbk’,解决不了了

**Comment by hankcs** [comment]
1. 我不太常用Python2，主要由 @Samurais 维护。你可以把异常堆栈贴出来，看看Python2用户能不能帮你。
1. 处理中文还是推荐用Python3，省了很多编码的烦恼。

**Comment by luluforever** [comment]
我的是python啊，今天在另外一台电脑上也试一试了，一样的问题 导入pyhanlp的时候出错

**Comment by luluforever** [comment]
是python3

**Comment by hankcs** [comment]
把异常堆栈贴出来，显示哪一行有问题。

**Comment by luluforever** [comment]
我明天贴一下，谢谢大佬了

**Comment by luluforever** [comment]
问题显示如下：
Downloading https://github.com/hankcs/HanLP/releases/download/v1.6.2/hanlp-1.6.2-release.zip to D:\python3.6\lib\site-packages\pyhanlp\static\hanlp-1.6.2-release.zip
100.00%, 1 MB, 121 KB/s, ETA 0 min 0 s
Traceback (most recent call last):
  File "C:/Users/Yue-pc/Desktop/学习/scikitlearn/4.2.py", line 1, in <module>
    import pyhanlp
  File "D:\python3.6\lib\site-packages\pyhanlp\__init__.py", line 33, in <module>
    from pyhanlp.static import STATIC_ROOT
  File "D:\python3.6\lib\site-packages\pyhanlp\static\__init__.py", line 273, in <module>
    if not hanlp_installed_data_path():
  File "D:\python3.6\lib\site-packages\pyhanlp\static\__init__.py", line 112, in hanlp_installed_data_path
    root = read_config()
  File "D:\python3.6\lib\site-packages\pyhanlp\static\__init__.py", line 245, in read_config
    for line in f:
UnicodeDecodeError: 'gbk' codec can't decode byte 0xac in position 3: illegal multibyte sequence

**Comment by hankcs** [comment]
原因是Windows默认gbk，请试试新版本：

```
pip install pyhanlp==0.1.28
```

**Comment by luluforever** [comment]
尝试了新版本，但是还是出现这种问题：
���� 02, 2018 10:55:23 ���� com.hankcs.hanlp.corpus.io.IOUtil readBytes
����: ��ȡD:python3.6libsite-packagespyhanlpstatic/data/dictionary/custom/CustomDictionary.txt.binʱ�����쳣java.io.FileNotFoundException: D:python3.6libsite-packagespyhanlpstatic\data\dictionary\custom\CustomDictionary.txt.bin (ϵͳ�Ҳ���ָ����·����)
���� 02, 2018 10:55:23 ���� com.hankcs.hanlp.dictionary.CustomDictionary load
����: �Զ���ʵ�D:python3.6libsite-packagespyhanlpstatic/data/dictionary/custom/CustomDictionary.txt��ȡ����java.io.FileNotFoundException: D:python3.6libsite-packagespyhanlpstatic\data\dictionary\custom\CustomDictionary.txt (ϵͳ�Ҳ���ָ����·����)
���� 02, 2018 10:55:23 ���� com.hankcs.hanlp.dictionary.CustomDictionary loadMainDictionary
����: ʧ�ܣ�D:python3.6libsite-packagespyhanlpstatic/data/dictionary/custom/CustomDictionary.txt
���� 02, 2018 10:55:23 ���� com.hankcs.hanlp.dictionary.CustomDictionary load
����: �Զ���ʵ�D:python3.6libsite-packagespyhanlpstatic/data/dictionary/custom/�ִ����ﲹ��ʿ�.txt��ȡ����java.io.FileNotFoundException: D:python3.6libsite-packagespyhanlpstatic\data\dictionary\custom\�ִ����ﲹ��ʿ�.txt (ϵͳ�Ҳ���ָ����·����)
���� 02, 2018 10:55:23 ���� com.hankcs.hanlp.dictionary.CustomDictionary loadMainDictionary
����: ʧ�ܣ�D:python3.6libsite-packagespyhanlpstatic/data/dictionary/custom/�ִ����ﲹ��ʿ�.txt
���� 02, 2018 10:55:23 ���� com.hankcs.hanlp.dictionary.CustomDictionary load
����: �Զ���ʵ�D:python3.6libsite-packagespyhanlpstatic/data/dictionary/custom/ȫ��������ȫ.txt��ȡ����java.io.FileNotFoundException: D:python3.6libsite-packagespyhanlpstatic\data\dictionary\custom\ȫ��������ȫ.txt (ϵͳ�Ҳ���ָ����·����)
���� 02, 2018 10:55:23 ���� com.hankcs.hanlp.dictionary.CustomDictionary loadMainDictionary
����: ʧ�ܣ�D:python3.6libsite-packagespyhanlpstatic/data/dictionary/custom/ȫ��������ȫ.txt
���� 02, 2018 10:55:23 ���� com.hankcs.hanlp.dictionary.CustomDictionary load
����: �Զ���ʵ�D:python3.6libsite-packagespyhanlpstatic/data/dictionary/custom/�����ʵ�.txt��ȡ����java.io.FileNotFoundException: D:python3.6libsite-packagespyhanlpstatic\data\dictionary\custom\�����ʵ�.txt (ϵͳ�Ҳ���ָ����·����)
���� 02, 2018 10:55:23 ���� com.hankcs.hanlp.dictionary.CustomDictionary loadMainDictionary
����: ʧ�ܣ�D:python3.6libsite-packagespyhanlpstatic/data/dictionary/custom/�����ʵ�.txt
���� 02, 2018 10:55:23 ���� com.hankcs.hanlp.dictionary.CustomDictionary load
����: �Զ���ʵ�D:python3.6libsite-packagespyhanlpstatic/data/dictionary/custom/�������ʵ�.txt��ȡ����java.io.FileNotFoundException: D:python3.6libsite-packagespyhanlpstatic\data\dictionary\custom\�������ʵ�.txt (ϵͳ�Ҳ���ָ����·����)
���� 02, 2018 10:55:23 ���� com.hankcs.hanlp.dictionary.CustomDictionary loadMainDictionary
����: ʧ�ܣ�D:python3.6libsite-packagespyhanlpstatic/data/dictionary/custom/�������ʵ�.txt
���� 02, 2018 10:55:23 ���� com.hankcs.hanlp.dictionary.CustomDictionary load
����: �Զ���ʵ�D:python3.6libsite-packagespyhanlpstatic/data/dictionary/custom/�Ϻ�����.txt��ȡ����java.io.FileNotFoundException: D:python3.6libsite-packagespyhanlpstatic\data\dictionary\custom\�Ϻ�����.txt (ϵͳ�Ҳ���ָ����·����)
���� 02, 2018 10:55:23 ���� com.hankcs.hanlp.dictionary.CustomDictionary loadMainDictionary
����: ʧ�ܣ�D:python3.6libsite-packagespyhanlpstatic/data/dictionary/custom/�Ϻ�����.txt
���� 02, 2018 10:55:23 ���� com.hankcs.hanlp.dictionary.CustomDictionary load
����: �Զ���ʵ�D:python3.6libsite-packagespyhanlpstatic/data/dictionary/person/nrf.txt��ȡ����java.io.FileNotFoundException: D:python3.6libsite-packagespyhanlpstatic\data\dictionary\person\nrf.txt (ϵͳ�Ҳ���ָ����·����)
���� 02, 2018 10:55:23 ���� com.hankcs.hanlp.dictionary.CustomDictionary loadMainDictionary
����: ʧ�ܣ�D:python3.6libsite-packagespyhanlpstatic/data/dictionary/person/nrf.txt
���� 02, 2018 10:55:23 ���� com.hankcs.hanlp.dictionary.CustomDictionary loadMainDictionary
����: û�м��ص��κδ���
���� 02, 2018 10:55:23 ���� com.hankcs.hanlp.dictionary.CustomDictionary loadMainDictionary
����: �Զ���ʵ�D:python3.6libsite-packagespyhanlpstatic/data/dictionary/custom/CustomDictionary.txt�����ڣ�java.io.FileNotFoundException: D:python3.6libsite-packagespyhanlpstatic\data\dictionary\custom\CustomDictionary.txt.bin (ϵͳ�Ҳ���ָ����·����)
���� 02, 2018 10:55:23 ���� com.hankcs.hanlp.dictionary.CustomDictionary <clinit>
����: �Զ���ʵ�[D:python3.6libsite-packagespyhanlpstatic/data/dictionary/custom/CustomDictionary.txt, D:python3.6libsite-packagespyhanlpstatic/data/dictionary/custom/�ִ����ﲹ��ʿ�.txt, D:python3.6libsite-packagespyhanlpstatic/data/dictionary/custom/ȫ��������ȫ.txt ns, D:python3.6libsite-packagespyhanlpstatic/data/dictionary/custom/�����ʵ�.txt, D:python3.6libsite-packagespyhanlpstatic/data/dictionary/custom/�������ʵ�.txt, D:python3.6libsite-packagespyhanlpstatic/data/dictionary/custom/�Ϻ�����.txt ns, D:python3.6libsite-packagespyhanlpstatic/data/dictionary/person/nrf.txt nrf]����ʧ��
���� 02, 2018 10:55:23 ���� com.hankcs.hanlp.corpus.io.IOUtil readBytes
����: ��ȡD:python3.6libsite-packagespyhanlpstatic/data/dictionary/CoreNatureDictionary.txt.binʱ�����쳣java.io.FileNotFoundException: D:python3.6libsite-packagespyhanlpstatic\data\dictionary\CoreNatureDictionary.txt.bin (ϵͳ�Ҳ���ָ����·����)
���� 02, 2018 10:55:23 ���� com.hankcs.hanlp.dictionary.CoreDictionary load
����: ���Ĵʵ�D:python3.6libsite-packagespyhanlpstatic/data/dictionary/CoreNatureDictionary.txt�����ڣ�java.io.FileNotFoundException: D:python3.6libsite-packagespyhanlpstatic\data\dictionary\CoreNatureDictionary.txt (ϵͳ�Ҳ���ָ����·����)
Traceback (most recent call last):
  File "C:/Users/Yue-pc/Desktop/学习/scikitlearn/4.2.py", line 2, in <module>
    print(HanLP.segment('你好，欢迎在Python中调用HanLP的API'))
jpype._jexception.ExceptionInInitializerErrorPyRaisable: java.lang.ExceptionInInitializerError

**Comment by hankcs** [comment]
Windows路径得加反斜杠，已经接近成功了，试试：

```
pip install pyhanlp==0.1.31
```

**Comment by luluforever** [comment]
感谢大佬这么认真帮忙解决，我再试试

**Comment by hankcs** [comment]
安装后还得修改D:/python3.6/lib/site-packages/pyhanlp/static/hanlp.properties这个文件的第一行

```
root=D:/python3.6/lib/site-packages/pyhanlp/static/
```

或者干脆删掉这个文件重新来过。

**Comment by Jie-Yuan** [comment]
按照官网配置完全正确啊还是报错：
[](url)
![image](https://user-images.githubusercontent.com/20265321/38182824-9dc40cda-366e-11e8-9d5e-bb5c7afb0c7b.png)

**Comment by luluforever** [comment]
成功解决了，我后面是手动下载data的，这文件比较大，手动下载会好一点，，谢谢大佬

**Comment by hankcs** [comment]
好的。
